function config = orb5_config(config)
%ORB5_CONFIG Shared defaults; supply a struct to override individual fields.
if nargin == 0, config = struct(); end
defaults = struct('path',pwd,'is_em',[],'Z',1,'mu',2, ...
    'ad_hoc',1,'profile_species','deuterium','wname','cgau3', ...
    'GAM',false,'smooth',false,'time_windows',[75 85], ...
    'avg_window',[140 160],'hysterisis',true,'zonal_slot',6, ...
    'density_factor',1.5668,'tau',1,'mass_ratios', ...
    struct('deuterium',1,'electrons',1/1836), ...
    'chi_scales',struct('deuterium',[],'electrons',1,'fast',[]), ...
    'theory_overlay',false,'time_units','normalized', ...
    'extra_plots',[],'visible','on');
defaults.theory_C=0;
defaults.theory=struct('lx',720,'tau',1,'n',40,'kappan',0.8028, ...
    'etai',2/0.8028,'q_polynomial',[2.52 -0.16 0.86], ...
    'chi_coefficient',1.6,'frequency_ratio',0.69/0.5,'smoothing_window',61);
names = fieldnames(defaults);
for k = 1:numel(names)
    if ~isfield(config,names{k}), config.(names{k}) = defaults.(names{k}); end
end
if isfield(config,'theory')
    fields=fieldnames(defaults.theory);
    for k=1:numel(fields)
        if ~isfield(config.theory,fields{k}), config.theory.(fields{k})=defaults.theory.(fields{k}); end
    end
end
config.h5File = fullfile(config.path,'orb5_res.h5');
config.inputFile = fullfile(config.path,'input');
end
